rm(list = ls(all.names = TRUE)) 
print(paste0(Sys.time(),": Session PID: ", Sys.getpid()))
system('chmod +x /Users/eab/Projects/adsb/gitignore/inputs/sys_cmd.sh')
system("/Users/eab/Projects/adsb/gitignore/inputs/sys_cmd.sh",wait=TRUE)
quit()